---
- debug: var=x509
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - x509_alias

- name: key for {{ x509.dn.cn }} does exist
  openssl_privatekey:
    path: "{{ x509.keydir }}/{{ x509.alias }}.key"
    size: 2048
    type: RSA
    group: "{{ x509.group }}"
    mode: 00640
...
