# vim: set ft=yaml ts=2 expandtab:
---

- debug: var=x509
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ansible_os_family in x509_supported_os_families

- name: get OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

...
