---

- debug: var=x509
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ansible_os_family in x509.supported_os_families

- name: get OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
...
