---
- name: csr for {{ x509_alias }} is absent
  with_items:
    - "{{ x509.certdir }}/{{ x509_alias }}.cnf"
    - "{{ x509.certdir }}/{{ x509_alias }}.csr"
  file:
    path: "{{ item }}"
    state: absent
    backup: true
...
