---
- debug: var=x509
  tags:
    - never
    - debug

- debug: var=x509_alias
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - x509_alias is defined

- name: include_tasks
  include_tasks:
    file: "{{ x509_state }}.yml"
...
