# vim: set ft=yaml ts=2 expandtab:
---
- debug: var=x509
  tags:
    - never
    - debug

- debug: var=x509.alias
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - x509.alias is defined

- name: include_tasks
  include_tasks:
    file: "{{ x509.state }}.yml"
...
