---
- name: files for {{ x509_alias }} are absent
  with_items:
    - "{{ x509.keydir }}/{{ x509_alias }}.key"
    - "{{ x509.certdir }}/{{ x509_alias }}.chain.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.cert"
  file:
    path: "{{ item }}"
    state: absent
  notify: notify for changed cert

- name: files for {{ x509_alias }} are absent
  with_items:
    - "{{ x509.keydir }}/{{ x509_alias }}.pem"
  file:
    path: "{{ item }}"
    state: absent
  notify: notify for changed private pem

- name: files for {{ x509_alias }} are absent
  with_items:
    - "{{ x509.keydir }}/{{ x509_alias }}.key"
    - "{{ x509.keydir }}/{{ x509_alias }}.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.root.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.chain.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.cnf"
    - "{{ x509.certdir }}/{{ x509_alias }}.csr"
  file:
    path: "{{ item }}"
    state: absent

- name: files for {{ x509_alias }} are absent
  with_items:
    - "{{ x509.keydir }}/{{ x509_alias }}.key"
    - "{{ x509.keydir }}/{{ x509_alias }}.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.root.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.chain.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.cnf"
    - "{{ x509.certdir }}/{{ x509_alias }}.csr"
  file:
    path: "{{ item }}"
    state: absent

- name: files for {{ x509_alias }} are absent
  with_items:
    - "{{ x509.keydir }}/{{ x509_alias }}.key"
    - "{{ x509.keydir }}/{{ x509_alias }}.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.root.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.chain.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.cnf"
    - "{{ x509.certdir }}/{{ x509_alias }}.csr"
  file:
    path: "{{ item }}"
    state: absent

- name: files for {{ x509_alias }} are absent
  with_items:
    - "{{ x509.keydir }}/{{ x509_alias }}.key"
    - "{{ x509.keydir }}/{{ x509_alias }}.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.root.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.chain.pem"
    - "{{ x509.certdir }}/{{ x509_alias }}.cert"
    - "{{ x509.certdir }}/{{ x509_alias }}.cnf"
    - "{{ x509.certdir }}/{{ x509_alias }}.csr"
  file:
    path: "{{ item }}"
    state: absent

...
