---

- block:
    - debug: var=playbook_dir
  tags:
    - debug
    - never

- name: certificate does exist
  copy:
    src: "{{ playbook_dir }}/{{ cert }}"
    dest: /tmp/{{ alias }}.cert

- name: root certificate does exist
  copy:
    src: "{{ playbook_dir }}/{{ root }}"
    dest: /tmp/{{ alias }}.rootcert

- name: managed key does exist
  when: key is defined
  copy:
    src: "{{ playbook_dir }}/{{ key }}"
    dest: /tmp/{{ alias }}.key
    mode: g-rwx,o-rwx

- name: unmanaged key does exist
  when: key is not defined
  block:
    - name: unmanaged key does exist
      file:
        path: /tmp/{{ alias }}.key
        mode: g-rwx,o-rwx
    - name: read in key
      command: cat /tmp/{{ alias }}.key
      check_mode: false
      register: __key
    - debug: var=__key
      tags:
        - debug
        - never

- name: pem file does exist
  template:
    src: pem.j2
    dest: /tmp/{{ alias }}.pem
    mode: g-rwx,o-rwx
