# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  when: x509_src.chain is defined
  assert:
    that:
      - x509_src.chain|type_debug == 'list'

- name: assertions
  assert:
    that:
      - x509_src.cert

- name: unmanaged key for {{ x509.alias }}
  when: key is not defined
  block:
    - name: unmanaged key for {{ x509.alias }} does exist
      file:
        path: "{{ x509.keydir }}/{{ x509.alias }}.key"
        mode: g-rwx,o-rwx
      notify: notifiying for changed key

    - name: read in key
      changed_when: false
      no_log: true
      command: cat "{{ x509.keydir }}/{{ x509.alias }}.key"
      check_mode: false
      register: __key

- name: certificate for {{ x509.alias }} does exist
  copy:
    src: "{{ x509.local_cert_store }}/{{ x509_src.cert }}"
    dest: "{{ x509.certdir }}/{{ x509.alias }}.cert"
    mode: 00644
    backup: true
  notify: notifiying for changed cert

- name: root certificate for {{ x509.alias }} does exist
  copy:
    src: "{{ x509.local_cert_store }}/{{ x509_src.root }}"
    dest: "{{ x509.certdir }}/{{ x509.alias }}.root.cert"
    backup: true

- debug: var=key
  tags:
    - never
    - debug

- name: managed key for {{ x509.alias }} does exist
  no_log: true
  when: key is defined
  copy:
    src: "{{ x509.local_cert_store }}/{{ key }}"
    dest: "{{ x509.keydir }}/{{ x509.alias }}.key"
    mode: g-rwx,o-rwx
    backup: true
  notify: notifiying for changed key

- name: unmanaged key for {{ x509.alias }}
  when: key is not defined
  block:
    - name: unmanaged key for {{ x509.alias }} does exist
      file:
        path: "{{ x509.keydir }}/{{ x509.alias }}.key"
        mode: g-rwx,o-rwx
      notify: notifiying for changed key

    - name: read in key
      changed_when: false
      no_log: true
      command: cat "{{ x509.keydir }}/{{ x509.alias }}.key"
      check_mode: false
      register: __key

- name: private pem file for {{ x509.alias }} does exist
  no_log: true
  template:
    src: pem.j2
    dest: "{{ x509.keydir }}/{{ x509.alias }}.pem"
    mode: g-rwx,o-rwx
    backup: true
  notify: notifiying for changed private pem

- name: chain file for {{ alias }} does exist
  template:
    src: chain.j2
    dest: "{{ x509.certdir }}/{{ x509.alias }}.chain.pem"
    mode: 0644
    backup: true

...
